# Generated by Django 4.0.3 on 2022-04-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
