# Generated by Django 4.0.3 on 2022-04-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_note_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='module',
        ),
    ]
