# Generated by Django 4.0.3 on 2022-04-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_note_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='module',
            field=models.CharField(default='其他', max_length=50, verbose_name='模块'),
        ),
    ]
