# Generated by Django 4.0.3 on 2022-04-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_note_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
    ]
