# Generated by Django 4.0.3 on 2022-05-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0005_note_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='praising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(default='文章', on_delete=django.db.models.deletion.CASCADE, to='article.note')),
                ('writer', models.ForeignKey(default='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
