# Generated by Django 4.0.3 on 2022-05-04 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0007_praising'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentchar', models.CharField(default='空', max_length=100, verbose_name='评论内容')),
                ('article', models.ForeignKey(default='文章', on_delete=django.db.models.deletion.CASCADE, to='article.note')),
                ('commentator', models.ForeignKey(default='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

    ]
