# Generated by Django 4.0.3 on 2022-05-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_comment_delete_praise'),
    ]

    operations = [
        migrations.AddField(
            model_name='praising',
            name='praiserid',
            field=models.IntegerField(default='0'),
        ),
    ]
